### ISSUE TITLE
Change compression formats

### ISSUE THREAD

**Issue by mrocklin** [conda-forge/conda-forge.github.io#982] opened 2020-02-16 16:56 UTC
*This started as a conversation on twitter [here](https://twitter.com/mrocklin/status/1228750299373817856)*

As of version 4.7, conda now supports different compression schemes other than bz2.  In particular, it supports z-standard, which is significantly faster to decompress.  This can result in a significantly faster user experience.

My understanding is that the build infrastructure exists to support the new compression schemes, but that anaconda.org doesn't yet support this.  Here is a comment from @mariusvniekerk 

> So unfortunately http://anaconda.org does not support the .conda file format yet

What are the next steps here?  Is this something that has to be done from within Anaconda Inc?  If so, is there a timeline for that, or are there ways that the community can help? cc @ericdill

**Comment by isuruf** [comment] 2020-02-16 17:02
Duplicate of #877

**Closed by isuruf** 2020-02-16 17:02 UTC

**Comment by mrocklin** [comment] 2020-02-16 17:18
Ah!  Thank you for the redirect!
