### ISSUE TITLE
Issue with the script tick-my-feedstocks

### ISSUE THREAD

**Issue by williamjamir** [conda-forge/conda-forge.github.io#510] opened 2018-01-11 23:46 UTC
Hi @pmlandwehr

I don't know if this is the correct place to report an issue but here it goes.

I was trying to run the script `tick_my_feedstocks.py` that is located inside the script folder and it crashed with the stack trace above:

I called the script passing the `--password` and `--user` arguments

This is the version of the packages:
```
python                   3.6.2 
beautifulsoup4      4.6.0  
conda-smithy        2.4.5  
gitpython               2.1.7  
jinja2                     2.10
pygithub                1.34 
pyyaml                  3.12  
requests                2.18.4  
tqdm                     4.19.5  
```

Stack trace:
```
Finding feedstock teams...: 14it [00:17,  1.24s/it]
Checking feedstock statuses...: 100%|██████████████████████████████████████████████████████████████| 12/12 [00:23<00:00,  1.99s/it]
Updating feedstocks: 100%|███████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.87s/it]
Regenerating feedstocks...:   0%|                                                                            | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tick.py", line 842, in <module>
    main()
  File "tick.py", line 838, in main
    args.skip_feedstocks)
  File "tick.py", line 719, in tick_feedstocks
    regenerate_fork(fork)
  File "tick.py", line 540, in regenerate_fork
    conda_smithy.configure_feedstock.main(local_repo_dir)
  File "/home/william/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 722, in main
    render_circle(env, config, forge_dir)
  File "/home/william/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 72, in render_circle
    with fudge_subdir('linux-64', build_config=meta_config(meta)):
  File "/home/william/miniconda3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/william/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 221, in fudge_subdir
    build_config.subdir = subdir
AttributeError: can't set attribute
```

**Comment by pmlandwehr** [comment] 2018-01-12 05:48
Hey sir - this is probably caused by issues with `conda-smithy` and its compatability with `conda` and `conda-build` versions. (See [here](https://github.com/conda-forge/conda-smithy/issues/545)) Please make sure that `conda-build` is only version 2 and that that `conda` is only version 4.3. That said, it's definitely a bit of a brittle program; thanks for reporting the issue.

**Comment by pelson** [comment] 2018-01-30 11:20
Yep, I agree that this is a dupe of https://github.com/conda-forge/conda-smithy/issues/545.

Please follow progress on this issue there @williamjamir. In the meantime, we may want to pin the conda-build version in the script (happy to accept a PR to do that).

HTH

**Closed by pelson** 2018-01-30 11:20 UTC
