### ISSUE TITLE
Azure MacOS-10.13 images will be removed by 23 March 2020

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#985] opened 2020-03-01 02:22 UTC
Seeing this on macOS builds on Azure. For example [here is one]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=126495&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c ).

> [warning]This pipeline uses a Microsoft-hosted agent image that will be removed on March 23, 2020 (MacOS-10.13). You must make changes to your pipeline before that date, or else your pipeline will fail. Learn more (https://aka.ms/removing-older-images-hosted-pools).
Pool: Azure Pipelines

cc @conda-forge/core

**Comment by isuruf** [comment] 2020-03-01 04:14
Duplicate of https://github.com/conda-forge/conda-smithy/issues/1234

**Closed by isuruf** 2020-03-01 04:14 UTC
