### ISSUE TITLE
One AppVeyor account per feedstock

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#47] opened 2016-03-17 19:30 UTC
The build queue on AppVeyor looks pretty backed up. Given this is all being run under one account, this is not too surprising. There are a number of ways to improve this. One might be to simply increase our bandwidth on AppVeyor (paid account). Though this could solve the problem temporarily, this will likely result in ratcheting into higher and higher bandwidths becoming prohibitively expensive. Another alternative would be to create a separate account for each feedstock. This allows are bandwidth to increase linearly with our feedstocks and thus should remain maintainable even with large numbers. The only question then is how best to set up this sort of behavior.

**Comment by pelson** [comment] 2016-03-21 09:09
Have you noticed this getting better since we made some of the AppVeyor queue changes, or is this still a bottleneck do you think?

**Comment by ocefpaf** [comment] 2016-03-21 11:30
It is much better, but I guess AppVeyor will always be a bottleneck. (It will get better once we get the bulk of `conda-recipes` converted to feedstocks.)

**Comment by jakirkham** [comment] 2016-03-21 12:19
I think it has been getting better, but I agree with @ocefpaf that this will likely remain a bottleneck. We can (and IMHO should) still try to tackle this in other ways like checking for `skip: True`. Though we should keep this in mind even though it may be tricky.

**Comment by jjhelmus** [comment] 2016-03-21 16:09
I think it should be possible to reduce the number of AppVeyor builds from six (one per platform and Python version) to two (one per platform) which may speeds things up a bit, especially for packages where one or more of the builds is skipped.  Rather than setting the Python version specification in the build matrix these could be set sequentially with multiple calls to conda-build-all.

**Comment by pelson** [comment] 2016-03-21 16:25
> Rather than setting the Python version specification in the build matrix these could be set sequentially with multiple calls to conda-build-all.

Agreed. We'd be trading off clarity for performance. That *is* reasonable, but I want to be certain we need to do it first - essentially, I think we should keep that up our sleeves if we want to speed things up beyond our current situation.

**Comment by janschulz** [comment] 2016-03-21 17:28
I don't think the setup for a build is the problem. E.g. looking at this: https://ci.appveyor.com/project/conda-forge/xonsh-feedstock/build/1.0.4

-> 2.7 wasn't build and took 1:15 minute
-> 3.4 was build and took 4 minutes

Taking the first as an indicator for the "setup", you only gain 1:15 per build... So for 6 -> 2 (only different python versions, no numpy versions), you gain 5 minutes... So from 20min down to 15min. Mpl is probably much worse due to much more compilation steps...

Other ideas/workarounds: 

* register a new appveyor account for every ~20 packages and switch accounts manually while doing the setup (manual, e.g. one commit every 20 packages in the staged-recipes repo, but currently it should still scale) or add 10 accounts in the staged-recipe scripts and assign them randomly to new packages (the first will still suck when x packages are merged at the same time)
* ask numfocus for a grant to pay for more appveyor power
* ask the conda guys if this could use build power from their builders? -> would need a rewrite of the conda-smithy infrastructure 
* ask appveyor for a upgrade-grant :-)

**Comment by janschulz** [comment] 2016-03-21 17:34
There is also this: https://ci.appveyor.com/project/conda-forge/protobuf-feedstock

Total build time: 2 hr 10 min
Sum of individual build times: ~12min

**Comment by jakirkham** [comment] 2016-03-21 17:40
@matthew-brett, mentioned over at NumPy that some open source projects have succeeded at getting more resources from AppVeyor by simply asking nicely. I don't know if we are in a situation where that would work for us. Though they do provide miniconda as an option with builds so they may be interested in a project that is trying to increase the diversity of packages available in that ecosystem. Then again we are using a **lot** of bandwidth.

**Comment by janschulz** [comment] 2016-03-21 17:51
Continuum wants to use the conda-forge packages in their (paid?) offerings, which might not what appveyor wants to pay for... On the other hand: 1200$ sounds cheap for continuum to get a happier conda-forge community :-)

**Comment by jakirkham** [comment] 2016-03-21 18:27
Interesting point. I didn't realize that some closed source stuff might appear here too. Will there be private recipe repos for these? Do we have some logic for that?

We should certainly consider how we want to increase our bandwidth on AppVeyor. Though there still are a few opportunities to shorten the queue/wait time by skipping builds or fast finishing them. When we make some more of these optimizations, we should reassess to see how bad the queue still is.

**Comment by janschulz** [comment] 2016-03-21 19:21
> Interesting point. I didn't realize that some closed source stuff might appear here too. Will there be private recipe repos for these? Do we have some logic for that?

sorry, I didn't mean closed source, but only things like contiuum copying some packages to their channel or using the conda-forge packages as selling argument.

**Comment by msarahan** [comment] 2016-03-21 19:48
We've been investigating package verification as a prerequisite for packages being moved/copied from conda-forge to default.  It's a lot more complicated than I anticipated.  Simple hashes don't work, because the hash of archives is sensitive to file modification times, as well as some crazy indeterminism in how files are added.

We (Continuum) probably won't immediately go down that road.  Instead, Conda-forge will be the canonical recipe source, and we will build our own package for the default channel.  Conda-forge packages will be mirrored/linked on the community channel.

Hopefully this helps with any time requests from Appveyor.  I will ask other people if Continuum can sponsor some time.

**Comment by janschulz** [comment] 2016-03-21 20:00
>  Simple hashes don't work, because the hash of archives is sensitive to file modification times, as well as some crazy indeterminism in how files are added.

If you want to go down that road: debian currently does the same with their reproducible builds... https://wiki.debian.org/ReproducibleBuilds

**Comment by msarahan** [comment] 2016-03-21 20:01
Yeah, we found that.  We also found that similar stuff doesn't work on Windows or on Mac. =(

**Comment by jakirkham** [comment] 2016-04-01 02:47
At some point, would you just be able to take what we have and use it in place of your existing builds? Once we have reproduced the stack, will there be any need for this verification?

**Comment by msarahan** [comment] 2016-04-01 02:58
I think it will be more for indemnification guarantees for paying customers.  If we can give them peace of mind in any way, it is valuable, no matter how unnecessary it might seem.

This is less about guaranteeing functionality (which I think conda forge handles well anyway with CI) and more about guaranteeing the absence of any malicious alterations.  Not to say that people shouldn't also trust conda forge, just that they trust businesses that they can directly hold accountable more.

**Comment by jakirkham** [comment] 2016-04-01 03:14
Sure, that makes sense. Corporate clients are within their rights in asking for verification.

**Comment by ocefpaf** [comment] 2016-04-01 10:10
> 4. Encourage users to add [skip appveyor] to commits where Windows builds don't happen.

I am terrible with git-hooks but if someone can come up with one that checks the `meta.yaml` for `skip:  # [Win]` and automatically adds the `[skip appveyor]` then we would have a tool to to users to "encourage" them :wink:

**Comment by ocefpaf** [comment] 2016-04-01 10:27
> Given these thoughts, I could imagine having 3 queues for AppVeyor being pretty successful.

I am following the queue very closely this week (cancelling staged-recipes builds that are skipping Windows, re-starting failing jobs, etc) I can say that 1 (staged-recipes) is the main problem.

**Comment by pelson** [comment] 2016-04-12 07:07
Thanks to the AppVeyor upgrade, I think we can close this for now. I'm not against revisiting if/when the need arises. 👍 
https://github.com/conda-forge/staged-recipes/issues/244

**Closed by pelson** 2016-04-12 07:07 UTC

**Comment by SylvainCorlay** [comment] 2016-10-26 21:15
The appveyor queue has been quite long lately. 8-10 hours to get a feedstock update through. Are you still considering a numfocus-supported appveyor account with more vms?

**Comment by SylvainCorlay** [comment] 2016-10-26 21:52
Giving the priority to `staged-recipes` over feedstocks causes feedstocks to never get built, because new PRs keeps coming on staged recipes.
