### ISSUE TITLE
Utility to propose PRs to include toolchain.

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/conda-forge.github.io#431] opened 2017-08-25 02:38 UTC
There are a few packages around that have C build artifacts that have shared objects that were built without toolchain.

We should make a tool that proposes a a diff to the package to ensure that toolchain is included in the build recipes and bump the build number similar to what we do for pushing smithy updates.

@ericdill

**Comment by msarahan** [comment] 2017-08-25 03:08
Before you spend too much time on this, you should probably take a look at how conda-build 3 can change recipes.  Here's an example: https://github.com/AnacondaRecipes/jpeg-feedstock/pull/1/files

I think toolchain could be replaced by that new mechanism.  That new mechanism has the same concept, but allows people to reuse the same recipe with different compilers more easily.

Our new compiler recipes are in this repo: https://github.com/AnacondaRecipes/aggregate

Specifically, gcc: https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-compilers-feedstock/recipe
llvm/clang: https://github.com/AnacondaRecipes/aggregate/tree/master/llvm-compilers-feedstock/recipe
Clang for osx (activation setting env vars in same vein as toolchain): https://github.com/AnacondaRecipes/aggregate/tree/master/clang
and visual studios (activation only): 
https://github.com/AnacondaRecipes/aggregate/tree/master/vs2008
https://github.com/AnacondaRecipes/aggregate/tree/master/vs2010
https://github.com/AnacondaRecipes/aggregate/tree/master/vs2015

**Comment by jakirkham** [comment] 2017-08-25 16:10
So @isuruf has been working on `toolchain3`, which should replace `toolchain` in conda-forge over the long term. It goes a bit beyond configuring the compiler as it allows for optionally using `ccache`. Also it is bit better behaved than the `toolchain` as it uses a wrapper script for the compiler instead of solely relying on environment variables. Though it may need some tweaks for some feedstocks. I'm not sure how this would fit with `conda-build` 3 ATM, but it is worth exploring.

**Comment by mingwandroid** [comment] 2017-08-25 16:47
Was this discussed anywhere? Can I read any of the design goals for `toolchain3`?

**Comment by isuruf** [comment] 2017-08-25 16:49
there's some description here, https://github.com/conda-forge/toolchain-feedstock/pull/23#issue-235431400
Note that the PR was reverted and a new package `toolchain3` was created.

**Comment by mingwandroid** [comment] 2017-08-25 16:50
I would encourage you to look closely at what we've done for compilers. We have built very recent compilers both GCC (7.1) and clang (4.0.1) based that guarantee compat. with the very latest C/C++ language features while maintaining compatibility with CentOS6 and macOS 10.9.

It would be very good if your toolchain3 package can be based on those.

**Comment by 183amir** [comment] 2017-09-02 15:55
@mingwandroid that's awesome. Are these compilers available for us to use?

**Comment by msarahan** [comment] 2017-09-02 16:02
Yes, they are on the c3i_test anaconda.org channel. The easiest way to use them is with conda build 3. See https://github.com/AnacondaRecipes/bzip2-feedstock for an example conversion of a cf recipe to using cb3. There's also possibly helpful comments at https://github.com/conda-forge/geos-feedstock/pull/25

**Comment by 183amir** [comment] 2017-09-28 19:25
@msarahan I am testing the compilers from the defaults channel.
```
gcc_linux-64                 7.2.0                hc7b1ceb_1  defaults
```
both gcc in Linux and clang in mac.

I realized that I need to use a centos 6 docker image to use it with this gcc 7.2, right?
The `conda_builder_linux` uses centos 5 though. Looking at https://hub.docker.com/u/continuumio/ I see that there is a new image called `conda-concourse-ci`. Is this the image that we should be using to compile packages on Linux so that they are compatible with the defaults channel? Is it something that is going to last and we can rely on? (these questions are not related to conda-forge)

**Comment by 183amir** [comment] 2017-09-28 21:48
Something related to this thread: I have tested these new compiler packages from ContinuumIO and basically there is no need for a toolchain package anymore. There might be some corner cases though that I have not seen.

**Comment by jakirkham** [comment] 2017-09-28 22:12
Could you please expand on how you tested them?

**Comment by 183amir** [comment] 2017-09-29 06:41
I have tested them locally to compile bob packages. The new compiler packages export the required flags which makes the toolchain package redundant. But, the compilers are very new which means you'll have trouble compiling ancient code.

**Comment by jakirkham** [comment] 2017-09-29 07:26
What OS were you using?

**Comment by 183amir** [comment] 2017-09-29 14:14
The conda-concourse-ci docker image

**Comment by jakirkham** [comment] 2017-09-29 14:19
I see. So the main point of the `toolchain` initially was to fix issues on macOS.

**Comment by mingwandroid** [comment] 2017-09-29 14:24
Try the macOS compilers. They seem to be working well.

**Comment by msarahan** [comment] 2017-09-29 14:25
The new compilers are not sensitive to what platform you use them on.  You can use any docker image you want (perhaps not alpine-based ones, but any glibc-based ones should be OK).

**Comment by msarahan** [comment] 2017-09-29 14:27
To clarify, the reason why they are not sensitive to this is because they include their own glibc and kernel headers.  These are used only at build time.

**Comment by jakirkham** [comment] 2017-09-29 14:45
Cool. I'll take a look. Probably not today, but am interested to try. Would be curious to know more about how `clang` was built for macOS. Really happy to see `gfortran` as a separate thing. 👍 How are we handling things like `libcxx`, `openmp`, `libgfortran` and such (thinking mainly about macOS here)?

**Comment by jakirkham** [comment] 2017-09-29 14:46
> The new compilers are not sensitive to what platform you use them on.

Meaning the Linux ones, right?

**Comment by mingwandroid** [comment] 2017-09-29 14:53
I basically copied conda-forge for gfortran and libgfortran in the interests of compatibility.

The macOS clang build script can be found on AnacondaRecipes/aggregate. You need to run it on macOS 10.9 though (same as the Linux ones need to be built on centos6), but after that, in theory you are free to use whatever more modern versions of those OSes you want to (caveats being glibc based on Linux and for some builds needing to turn off SIP on macOS).

**Comment by mingwandroid** [comment] 2017-09-29 14:55
These lower bounds for the build OS is so we can make the same compatibility guarantees about those persisted as we can for the rest of the ecosystem.

**Comment by jakirkham** [comment] 2017-09-29 15:17
> ... for some builds needing to turn off SIP on macOS

Could you please elaborate on why this is?

**Comment by mingwandroid** [comment] 2017-09-29 15:29
> Could you please elaborate on why this is?

This restriction has nothing to do with these toolchains and exist with Apple's existing toolchain (well, really, the restriction has nothing to do with any toolchains). The issue is that SIP scrubs the `DYLD_` family of env. vars in one of the most developer unfriendly features I've ever seen an OS implement:

https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html

**Comment by mingwandroid** [comment] 2017-09-29 15:37
You've probably never run into this by using macOS 10.10 (or lower or macOS > 10.10 with SIP disabled).

For some Autotools-based projects, adding `-Wl,-rpath,${PREFIX}/lib` is enough of a workaround, but for ones that generate their own shared libraries and then also use them in-build (common for `make check`) it is not, you may need to add multiple `-Wl,-rpath,<something>` to make those work.

**Comment by jakirkham** [comment] 2020-02-10 08:06
Closing this out as it is no longer relevant.

**Closed by jakirkham** 2020-02-10 08:06 UTC
