### ISSUE TITLE
Installing from conda-forge breaks conda's installation

### ISSUE THREAD

**Issue by drorata** [conda-forge/conda-forge.github.io#547] opened 2018-03-21 11:34 UTC
I tried to install `cookiecutter` and `jupyter_contrib_nbextensions` from `conda-forge`. In both cases, the last step in the plan was:

```
The following packages will be DOWNGRADED:

    conda:           4.5.0-py36_0                      --> 4.3.34-py36_0    conda-forge
```

Going forward with this ends up with a broken `conda` installation!!!

I opened an issue on https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1267 but I believe this is a more general problem given that it happens also with `cookiecutter`.

**Comment by jankatins** [comment] 2018-03-21 12:07
Probably at some time fixed by https://github.com/conda-forge/conda-feedstock/pull/42

**Comment by drorata** [comment] 2018-03-21 12:32
@jankatins What do you mean?

**Comment by jankatins** [comment] 2018-03-21 13:04
The problem is that conda prefers one channel over the other and will downgrade packages which are in a lower version of the preferred channel. In this case the default channel updated conda, but conda-forge has not yet done that. And you prefer the conda-forge channel above the default channel. 

There are probably also nowadays ways to pin a package to a channel or so. Haven't investigated yet...

**Comment by CJ-Wright** [comment] 2018-03-21 13:27
Would it be possible to post the traceback for the conda error(s) you are getting? That might give us more info on what broke.

**Comment by jakirkham** [comment] 2018-03-21 13:36
Any reason not to use a different environment?

**Comment by drorata** [comment] 2018-03-22 08:48
@CJ-Wright I am not sure what you mean. What errors? As mentioned in https://github.com/conda-forge/conda-feedstock/issues/43 `conda` is no longer available after the downgrade.

@jakirkham I wanted to install `cookiecutter` on my base environment so it will be available across the board.

**Comment by dougalsutherland** [comment] 2018-03-22 14:13
@drorata The problem is the `conda` shell integration; your actual installation should still be okay. See the end of https://github.com/conda-forge/conda-feedstock/issues/43#comment-375152359 for instructions on how to work around the problem until we can get the new `conda` version on conda-forge.

**Comment by sdmcclure** [comment] 2018-07-11 15:59
Thanks for comments and help on this issue so far. I think I've run into the same problem, although I appear to have an up to date version of conda. Is there a way to restore conda on my machine (Windows with Anaconda distribution).

I had been using only default channels and installed the miktex package from conda-forge with:
conda install -c conda-forge miktex

This upgraded and downgraded several packages now conda is not working. conda list works, but conda search gives a loading channels error and conda upgrade gives an environment error.  Conda list shows that I have version 4.5.6 with conda-forge as the channel. I tried altering my condarc file (previously empty) and specifying default first, and then conda-forge. 

Is there a way to restore conda so that I can continue to use the default channel? I'm a reluctant to switch my primary channel to conda-forge until I learn more about it. I was unfamiliar with the concept of channels before I encountered this problem.

Here is the error report if that's helpfull:

`C:\>conda update conda                                                          Solving environment: failed                                                                                                                                     # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<                                                                                                        Traceback (most recent call last):                                                File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__                                                                                  return func(*args, **kwargs)                                                  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main                                                                                        exit_code = do_call(args, p)                                                  File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call                                                                            exit_code = getattr(module, func_name)(args, parser)                          File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 14, in execute                                                                               install(args, parser, 'update')                                               File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 235, in install                                                                                  force_reinstall=context.force,                                                File "C:\Anaconda3\lib\site-packages\conda\core\solve.py", line 506, in solve_for_transaction                                                                     force_remove, force_reinstall)                                                File "C:\Anaconda3\lib\site-packages\conda\core\solve.py", line 439, in solve_for_diff                                                                            final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)                                                                       File "C:\Anaconda3\lib\site-packages\conda\core\solve.py", line 180, in solve_final_state                                                                         index, r = self._prepare(prepared_specs)                                      File "C:\Anaconda3\lib\site-packages\conda\core\solve.py", line 580, in _prepare                                                                                  self.subdirs, prepared_specs)                                                 File "C:\Anaconda3\lib\site-packages\conda\core\index.py", line 215, in get_reduced_index                                                                         new_records = query_all(spec)                                                 File "C:\Anaconda3\lib\site-packages\conda\core\index.py", line 184, in query_all                                                                                 return tuple(concat(future.result() for future in as_completed(futures)))                                                                                     File "C:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 94, in query                                                                                self.load()                                                                   File "C:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 148, in load                                                                                _internal_state = self._load()                                                File "C:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 216, in _load                                                                               mod_etag_headers.get('_mod'))                                                 File "C:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 416, in fetch_repodata_remote_request                                                       timeout=timeout)                                                              File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get                                                                                      return self.request('GET', url, **kwargs)                                     File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 479, in request                                                                                  prep.url, proxies, stream, verify, cert                                       File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 654, in merge_environment_settings                                                               env_proxies = get_environ_proxies(url) or {}                                  File "C:\Anaconda3\lib\site-packages\requests\utils.py", line 617, in get_environ_proxies                                                                         if should_bypass_proxies(url):                                              TypeError: should_bypass_proxies_patched() missing 1 required positional argument: 'no_proxy'                                                                                                                                               `$ C:\Anaconda3\Scripts\conda update conda`                                                                                                                       environment variables:                                                                         CIO_TEST=<not set>                                                            CONDA_ROOT=C:\Anaconda3                                                           HOMEPATH=\                                                                          PATH=C:\Anaconda3\Library\bin;C:\ProgramData\Oracle\Java\javapath;C:\Progra                                                                                          m Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files                                                                                             (x86)\Common Files\Microsoft Shared\Windows Live;c:\Program Files                                                                                               (x86)\AMD APP\bin\x86_64;c:\Program Files (x86)\AMD                             APP\bin\x86;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program                                                                                                Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\Sys                                                                                          tem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program                                                                                               Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files                                                                                               (x86)\Windows Live\Shared;C:\GWV6\;C:\GWV6\gdal\bin;C:\Program                                                                                                  Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program                                                                                                Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files                                                                                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files                                                                                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Anaconda3;C:\                                                                                          Anaconda3\Scripts;C:\Anaconda3\Library\bin;C:\Program                           Files\Git\cmd;%MAINDIR%                                            PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\          REQUESTS_CA_BUNDLE=<not set>                                                         SSL_CERT_FILE=<not set>                                                                                                                                  active environment : None                                                         user config file : C:\Users\smcclure\.condarc                             populated config files : C:\Users\smcclure\.condarc                                      conda version : 4.5.6                                                     conda-build version : 1.20.0                                                         python version : 3.5.1.final.0                                                base environment : C:\Anaconda3  (writable)                                         channel URLs : https://repo.anaconda.com/pkgs/main/win-64                                      https://repo.anaconda.com/pkgs/main/noarch                                      https://repo.anaconda.com/pkgs/free/win-64                                      https://repo.anaconda.com/pkgs/free/noarch                                      https://repo.anaconda.com/pkgs/r/win-64                                         https://repo.anaconda.com/pkgs/r/noarch                                         https://repo.anaconda.com/pkgs/pro/win-64                                       https://repo.anaconda.com/pkgs/pro/noarch                                       https://repo.anaconda.com/pkgs/msys2/win-64                                     https://repo.anaconda.com/pkgs/msys2/noarch                                     https://conda.anaconda.org/conda-forge/win-64                                   https://conda.anaconda.org/conda-forge/noarch                   package cache : C:\Anaconda3\pkgs                                                               C:\Users\smcclure\AppData\Local\conda\conda\pkgs             envs directories : C:\Anaconda3\envs                                                               C:\Users\smcclure\AppData\Local\conda\conda\envs                                C:\Users\smcclure\.conda\envs                                        platform : win-64                                                             user-agent : conda/4.5.6 requests/2.12.4 CPython/3.5.1 Windows/7 Windows/6.1.7601                                                                            administrator : False                                                              netrc file : None                                                             offline mode : False                                                                                                                                                                                                                 An unexpected error has occurred. Conda has prepared the above report.          If submitted, this report will be used by core maintainers to improve           future releases of conda.                                                       Would you like conda to send this report to the core maintainers?               [y/N]: y                                                                        Upload did not complete.                                                        Thank you for helping to improve conda.                                         Opt-in to always sending reports (and not see this message again)               by running                                                                                                                                                          $ conda config --set report_errors true `

**Comment by CJ-Wright** [comment] 2018-07-11 16:21
@sdmcclure Would it be possible to re-format the traceback that you posted? It is very difficult to read in it's current format.

**Comment by sdmcclure** [comment] 2018-07-11 16:43
Sorry for the poor formatting initially. Hopefully it's more legible now

**Comment by CJ-Wright** [comment] 2018-07-11 16:47
@sdmcclure is it possible to also post the current env? (`conda list`)?
I suspect that his has to do with `requests` going `noarch`.

**Comment by sdmcclure** [comment] 2018-07-11 18:08
Sure:

```
C:\>conda list                                                                
# packages in environment at C:\Anaconda3:                                    #                                                                             # Name                    Version                   Build  Channel            
alabaster                 0.7.7                    py35_0                     
anaconda                  custom           py35h64770cb_0                     
anaconda-client           1.4.0                    py35_0                     
anaconda-navigator        1.8.4                    py35_0                     
anaconda-project          0.8.2            py35h06aeb26_0                     
argcomplete               1.0.0                    py35_1                     
astroid                   1.6.5                    py35_0                     
astropy                   2.0.7            py35h452e1ab_1                     
babel                     2.2.0                    py35_0                     
beautifulsoup4            4.4.1                    py35_0                     
bitarray                  0.8.1                    py35_1                     
blaze                     0.9.1                    py35_0                     
bleach                    2.1.3                    py35_0                     
blosc                     1.14.3               he51fdeb_0                     
bokeh                     0.11.1                   py35_0                     
boost                     1.66.0              py35_vc14_1  [vc14]  conda-forge
boost-cpp                 1.66.0                   vc14_1  [vc14]  conda-forge
boto                      2.39.0                   py35_0                     
bottleneck                1.2.1            py35h8a3671c_0                     
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge
ca-certificates           2018.4.16                     0    conda-forge      
certifi                   2018.4.16                py35_0    conda-forge      
cffi                      1.5.2                    py35_0                     
chardet                   3.0.4            py35h177e1b7_1                     
chest                     0.2.3                    py35_0                     
click                     6.7              py35h10df73f_0                     
click-plugins             1.0.3                    py35_0                     
cligj                     0.4.0                    py35_0                     
cloudpickle               0.1.1                    py35_0                     
clyent                    1.2.1                    py35_0                     
colorama                  0.3.7                    py35_0                     
comtypes                  1.1.2                    py35_0                     
conda                     4.5.6                    py35_0    conda-forge      
conda-build               1.20.0                   py35_0                     
conda-env                 2.6.0                h36134e3_1                     
conda-manager             0.4.0                    py35_0                     
configobj                 5.0.6                    py35_0                     
console_shortcut          0.1.1                    py35_1                     
cryptography              1.7.1                    py35_0                     
curl                      7.60.0                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                   py35_0                     
cython                    0.23.4                   py35_0                     
cytoolz                   0.9.0.1          py35hfa6e2cd_0                     
dask                      0.8.1                    py35_0                     
datashape                 0.5.1                    py35_0                     
decorator                 4.0.9                    py35_0                     
descartes                 1.1.0                    py35_0                    
dill                      0.2.4                    py35_0                     
docutils                  0.14             py35h8ccb97f_0                     
dynd-python               0.7.2                    py35_0                     
entrypoints               0.2.3            py35hb91ced9_2                     
et_xmlfile                1.0.1                    py35_0                     
expat                     2.2.5                    vc14_0  [vc14]  conda-forge
fastcache                 1.0.2                    py35_0                     
fiona                     1.7.10           py35hefe5c53_0                     
flask                     0.10.1                   py35_1                     
flask-cors                2.1.2                    py35_0                    
 flopy                     3.2.4                     <pip>                     
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
freexl                    1.0.2                    vc14_2  [vc14]  conda-forge
gdal                      2.2.2            py35h202a4aa_1                     
geopandas                 0.3.0                    py35_0                     
geos                      3.6.2                h9ef7328_2                     
geotiff                   1.4.2                    vc14_1  [vc14]  conda-forge
gevent                    1.1.0                    py35_0                     
greenlet                  0.4.9                    py35_0                     
h5py                      2.8.0            py35hfa6e2cd_0    conda-forge      
hdf4                      4.2.13                   vc14_0  [vc14]  conda-forge
hdf5                      1.10.1                   vc14_2  [vc14]  conda-forge
heapdict                  1.0.0                    py35_0                     
html5lib                  1.0.1            py35h047fa9f_0                     
icc_rt                    2017.0.4             h97af966_0                     
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.0                      py35_0                     
imageio                   2.3.0                    py35_0                     
ipykernel                 4.3.1                    py35_0                     
ipython                   4.1.2                    py35_1                     
ipython_genutils          0.1.0                    py35_0                     
ipywidgets                4.1.1                    py35_0                     
isort                     4.3.4                    py35_0                     
itsdangerous              0.24                     py35_0                     
jdcal                     1.2                      py35_0                     
jedi                      0.9.0                    py35_0                     
jinja2                    2.8                      py35_0                     
jpeg                      9b                       vc14_2  [vc14]  conda-forge
jsonschema                2.4.0                    py35_0                     
jupyter                   1.0.0                    py35_4                     
jupyter_client            4.2.2                    py35_0                     
jupyter_console           4.1.1                    py35_0                     
jupyter_core              4.1.0                    py35_0                     
kealib                    1.4.7                    vc14_4  [vc14]  conda-forge
kiwisolver                1.0.1            py35hc605aed_0                     
krb5                      1.14.6                   vc14_0  [vc14]  conda-forge
launcher                  1.0.0                         4                     
lazy-object-proxy         1.3.1            py35he996729_0                     
libboost                  1.65.1               he51fdeb_4                    
libdynd                   0.7.2                         0                     
libgdal                   2.2.4                    vc14_5  [vc14]  
conda-forgelibiconv                  1.14                     vc14_4  [vc14]  conda-forge
libkml                    1.3.0                    vc14_6  [vc14]  conda-forge
libnetcdf                 4.6.1                    vc14_2  [vc14]  conda-forge
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libpq                     9.6.3                    vc14_0  [vc14]  conda-forge
libsodium                 1.0.16                   vc14_0  [vc14]  conda-forge
libspatialindex           1.8.5                    vc14_1  [vc14]  conda-forge
libspatialite             4.3.0a                  vc14_19  [vc14]  conda-forge
libssh2                   1.8.0                    vc14_2  [vc14]  conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_1  [vc14]  conda-forge
llvmlite                  0.23.2           py35he51fdeb_0                     
locket                    0.2.0                    py35_0                     
lxml                      3.6.0                    py35_0                     
lzo                       2.10                     vc14_0  [vc14]  conda-forge
markupsafe                0.23                     py35_1                     
matplotlib                2.2.2                    py35_1    conda-forge      
mccabe                    0.6.1            py35hcf31250_1                     
menuinst                  1.3.2                    py35_0                     
miktex                    2.9.6621             h2fa13f4_0    conda-forge      
mistune                   0.7.2                    py35_0                     
mkl                       2017.0.3                      0                     
mkl-service               1.1.2                    py35_3                     
mpmath                    0.19                     py35_0                     
multipledispatch          0.4.8                    py35_0                     
munch                     2.3.2                    py35_0                     
nbconvert                 5.3.1            py35h98d6c46_0                     
nbformat                  4.4.0            py35h908c9d9_0                     
networkx                  1.11                     py35_0                     
nltk                      3.2                      py35_0                     
node-webkit               0.10.1                        0                     
nose                      1.3.7                    py35_0                     
notebook                  4.2.1                    py35_0                     
numba                     0.38.1           py35h830ac7b_0                     
numexpr                   2.6.2               np113py35_0                     
numpy                     1.13.1                   py35_0                     
odo                       0.4.2                    py35_0                     
olefile                   0.45.1                   py35_0                     
openjpeg                  2.3.0                    vc14_2  [vc14]  conda-forge
openpyxl                  2.3.2                    py35_0                     
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
pandas                    0.20.3                   py35_0                     
pandoc                    2.2.1                h1a437c5_0                     
pandocfilters             1.4.2            py35h978f723_1                     
partd                     0.3.2                    py35_1                     
patch                     2.5.9                         1                     
path.py                   8.1.2                    py35_1                     
patsy                     0.5.0                    py35_0                     
pep8                      1.7.0                    py35_0                     
PestTools                 0.0.1                     <pip>                     
pickleshare               0.5                      py35_0                     
pillow                    4.2.1            py35hd7da350_0                     
pip                       9.0.1                    py35_1                     
pip                       9.0.1                     <pip>                     
ply                       3.8                      py35_0                     
proj4                     4.9.3                    vc14_5  [vc14]  conda-forge
psutil                    4.1.0                    py35_0                     
psycopg2                  2.7.5                    py35_0    conda-forge      
py                        1.4.31                   py35_0                     
pyasn1                    0.1.9                    py35_0                     
pycosat                   0.6.3            py35h456c199_0                     
pycparser                 2.14                     py35_0                     
pycrypto                  2.6.1                    py35_3                     
pyemu                     0.1                       <pip>                     
pyflakes                  1.1.0                    py35_0                     
pygments                  2.1.1                    py35_0                     
pylint                    1.9.2                    py35_0                     
pyopenssl                 16.2.0                   py35_0                     
pyparsing                 2.0.3                    py35_0                     
pyproj                    1.9.5.1                  py35_0                     
pyqt                      5.6.0                    py35_2                     
pyreadline                2.1                      py35_0                     
pysal                     1.14.3                   py35_0                     
pyshp                     1.2.10                    <pip>                     
pytables                  3.4.4                    py35_8    conda-forge      
pytest                    2.8.5                    py35_0                     
python                    3.5.1                         4                     
python-dateutil           2.5.1                    py35_0                     
pytz                      2016.2                   py35_0                     
pywavelets                0.5.2            py35h7c47ace_0                     
pywin32                   220                      py35_1                     
pyyaml                    3.11                     py35_3                     
pyzmq                     15.2.0                   py35_0                     
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtawesome                 0.3.2                    py35_0                     
qtconsole                 4.3.1            py35hc47b0dd_0                     
qtpy                      1.4.2                    py35_0                     
requests                  2.12.4                   py35_0                     
rope                      0.9.4                    py35_1                     
rtree                     0.8.3                    py35_0                     
ruamel_yaml               0.11.14                  py35_1                     
scikit-image              0.13.1           py35hfa6e2cd_1                     
scikit-learn              0.19.0              np113py35_0                     
scipy                     0.19.1              np113py35_0                     
setuptools                39.2.0                   py35_0                     
shapely                   1.6.2            py35h2f425f0_0                     
simplegeneric             0.8.1                    py35_0                     
singledispatch            3.4.0.3                  py35_0                     
sip                       4.19.8           py35h6538335_0                     
six                       1.10.0                   py35_0                     
snappy                    1.1.7                    vc14_1  [vc14]  conda-forge
snowballstemmer           1.2.1                    py35_0                     
sockjs-tornado            1.0.1                    py35_0                     
sphinx                    1.3.5                    py35_0                     
sphinx_rtd_theme          0.1.9                    py35_0                     
spyder                    3.0.2                    py35_0                     
sqlalchemy                1.0.12                   py35_0                     
sqlite                    3.20.1                   vc14_2  [vc14]  conda-forge
statsmodels               0.9.0            py35h452e1ab_0                     
sympy                     1.0                      py35_0                     
testpath                  0.3.1            py35h06cf69e_0                     
tk                        8.6.7                    vc14_0  [vc14]  conda-forge
toolz                     0.9.0                    py35_0                     
tornado                   4.3                      py35_0                     
traitlets                 4.2.1                    py35_0                     
unicodecsv                0.14.1                   py35_0                     
vc                        14                            0                     
vs2015_runtime            14.00.23026.0                 0                     
webencodings              0.5.1            py35h5d527fb_1                     
werkzeug                  0.11.4                   py35_0                     
wheel                     0.29.0                   py35_0                     
wincertstore              0.2              py35hfebbdb8_0                     
wrapt                     1.10.11          py35h54666f7_0                     
xerces-c                  3.2.0                    vc14_0  [vc14]  conda-forge
xlrd                      0.9.4                    py35_0                     
xlsxwriter                0.8.4                    py35_0                     
xlwings                   0.7.0                    py35_0                     
xlwt                      1.0.0                    py35_0                     
xz                        5.2.4                h2fa13f4_4                     
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

```

**Comment by isuruf** [comment] 2018-07-11 18:14
https://github.com/conda/conda/issues/7524. Original issue is fixed now

**Closed by isuruf** 2018-07-11 18:14 UTC

**Comment by sdmcclure** [comment] 2018-07-11 20:11
@isuruf Thanks! This solution worked for me.

**Comment by DonAurelio** [comment] 2019-09-07 02:48
I solve this problem installing the version 4.6.14 of conda as suggested on this issue [9004](https://github.com/conda/conda/issues/9004) before perform further installs.

`conda install conda=4.6.14
`
It looks like further versions of conda are introducing this error.
