### ISSUE TITLE
Python 3.5 packages contain extra .pyc files

### ISSUE THREAD

**Issue by aburgm** [conda-forge/conda-forge.github.io#264] opened 2016-11-08 03:40 UTC
Several python 3.5 conda packages such as pandas and pytz contain unrelated .pyc files in `__pycache__` directories, e.g. for pkg_resourecs, setuptools or Cython. See for example:

https://anaconda.org/conda-forge/pandas/0.19.1/download/win-64/pandas-0.19.1-np111py35_0.tar.bz2
https://anaconda.org/conda-forge/pytz/2016.7/download/win-64/pytz-2016.7-py35_0.tar.bz2

The python 3.4 versions don't contain these extra files:

https://anaconda.org/conda-forge/pandas/0.19.1/download/win-64/pandas-0.19.1-np111py34_0.tar.bz2
https://anaconda.org/conda-forge/pytz/2016.7/download/win-64/pytz-2016.7-py34_0.tar.bz2

This issue is not specific to Windows, it also happens on Linux and Mac OS X.

The reason why this happens is that for Python 3.5, conda-build does not create `__pycache__` directories and instead creates the `.pyc` files on the same level as the corresponding `.py` files. When such a package is a build-time dependency for another package, e.g. setuptools for pytz, this leads to the `__pycache__` directories getting created at the time setup.py is run, and the newly created `__pycache__` directories make their way into the built conda package.

This [has been fixed](https://github.com/conda/conda-build/pull/1304) in conda-build recently, but needs at least conda-build 2.0.2. I understand at the moment, conda-forge packages are still built with conda-build 1. I expect that once conda-forge supports conda-build 2, affected packages have to be rebuilt starting at the bottom of the stack to fix this properly.

A suggested workaround by @marscher is to basically use `python -B setup.py install --single-version-externally-managed --record=record.txt` in the recipe. The `-B` flag prevents bytecode files to be written during execution of `setup.py`, and conda-build creates the needed pyc files separately anyway. However, it does not solve the root cause of the problem (which is the build-time dependency packages not having their own `__pycache__` directories).

Posting this issue on this repo as suggested by @jakirkham in https://github.com/conda-forge/conda-smithy/issues/373.

**Comment by jakirkham** [comment] 2016-11-15 06:58
Thanks for the write-up @aburgm .

**Comment by jakirkham** [comment] 2016-11-15 06:58
cc @conda-forge/core

**Comment by jjhelmus** [comment] 2016-11-15 16:27
IIRC this is caused by a bug in conda build 1.x which was fixed in 2.x.  Upgrading to conda build 2 and rebuilding Python 3.5 should results in the __pycache__ directory being corrected and no .pyc files.  More details in conda-forge/python-feedstock#70

Thanks for tracking this down @aburgm

**Comment by jakirkham** [comment] 2017-01-13 05:42
So we are now on `conda-build` 2. As such I believe this is (or soon will be) resolved. Am going to close out this issue. Please let feedstock maintainers know if they have issues. Also offering a simple build number bump PR should be sufficient for rebuilding packages with `conda-build` 2 that will not have these issues. Thanks again for raising this.

**Closed by jakirkham** 2017-01-13 05:42 UTC
