### ISSUE TITLE
`channels/sources` in `conda-forge.yml` not respected?

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-forge.github.io#1495] opened 2021-08-14 02:30 UTC
Not sure if this is just a documentation problem or a Conda-smithy problem: [Here](https://conda-forge.org/docs/maintainer/conda_forge_yml.html#channels) it documents that `conda-forge.yml` allows setting the channel sources:
```yaml
channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - conda-forge
    - defaults
```
However, after making changes and rerendering this doesn't seem to make any difference. Instead, `channel_sources` should be set in `recipe/conda_build_config.yaml`.

**Comment by isuruf** [comment] 2021-08-14 04:15
Duplicate of https://github.com/conda-forge/conda-smithy/issues/897

**Closed by isuruf** 2021-08-14 04:15 UTC

**Comment by leofang** [comment] 2021-08-14 04:23
Thanks, @isuruf!
