### ISSUE TITLE
Brief Introduction page of  conda-forge( Reference: issue #374 )

### ISSUE THREAD

**Issue by prachi237** [conda-forge/conda-forge.github.io#1323] opened 2021-04-05 09:43 UTC
I took the reference from the issue  #374  I would like make changes in the brief introduction page of conda-forge documentation.
would like to re-structure the page and give  a precise and brief intro of conda-forge. we can define that as mentioned in https://anaconda.org/conda-forge  i.e "A community-led collection of recipes, build infrastructure, and distributions for the conda package manager."

![Screenshot (104)](https://user-images.githubusercontent.com/72700861/113560974-838bda80-9621-11eb-88ee-06da04c273d9.png)

![Screenshot (105)](https://user-images.githubusercontent.com/72700861/113560601-dc0ea800-9620-11eb-9895-2cde91edc019.png)
The two questions that are mentioned in the What is conda-forge introduction, instead of answering these two questions in what is conda-forge, they can be shown in FAQ section (in-fact one of the question is already present in FAQ section.

**Comment by benny-coy** [comment] 2021-04-05 10:21
# Outreachy applicant 2021
Please can i work on this issue?
pls assign me.

**Comment by prachi237** [comment] 2021-04-05 10:54
> # Outreachy applicant 2021
> Please can i work on this issue?
> pls assign me.

I would like to work on it 😄

**Comment by prachi237** [comment] 2021-04-05 11:10
> # Outreachy applicant 2021
> Please can i work on this issue?
> pls assign me.

since, even u r an outreachy applicant I would suggest u to go thru the issues that r labeled with ``docs``.

**Comment by PrernaSingh587** [comment] 2021-04-05 11:10
I think we should not entirely remove this section from the intro. It forms the basis. FAQ is for more of technical (and profound) questions. Introduction should definitely have this part. Just my perspective. :)
What do you think @viniciusdc ?

**Comment by prachi237** [comment] 2021-04-05 11:18
> I think we should not entirely remove this section from the intro. It forms the basis. FAQ is for more of technical (and profound) questions. Introduction should definitely have this part. Just my perspective. :)
> What do you think @viniciusdc ?

What I  think, someone who is new to  the org, won't be installing the packages or contribute  in the first sight. He/she will first flick through the documentation first, and that is the main purpose of having a documentation for an organization. Hence according tto me we shd keep the intro brief  and those questions can be added in the relevent sections, infact we have a complete separate section for that, reading those will make every thing clear for a new user.

**Comment by PrernaSingh587** [comment] 2021-04-05 11:25
> > I think we should not entirely remove this section from the intro. It forms the basis. FAQ is for more of technical (and profound) questions. Introduction should definitely have this part. Just my perspective. :)
> > What do you think @viniciusdc ?
> 
> What I think, someone who is new to the org, won't be installing the packages or contribute in the first sight. He/she will first flick through the documentation first, and that is the main purpose of having a documentation for an organization. Hence according tto me we shd keep the intro brief and those questions can be added in the relevent sections, infact we have a complete separate section for that, reading those will make every thing clear for a new user.

But we also have to make it look appealing to them. If there is not a proper introduction, that might be a turn off. When we read something or start to watch something, the intro is what makes the first impression on us. We can't remove the What and Why conda-forge section for sure, that would not be good according to me. And @viniciusdc  could better answer if we require a separate section for anything. Though I would still agree with you that the intro has to be re-modified any how. :)

**Comment by PrernaSingh587** [comment] 2021-04-05 11:26
> In addition in the issue #374 @ocefpaf had defined conda-forge really well, as someone new to org can easily understand it's purposesweat_smilesmile

I think we can take insights from it and come up with something good to redefine the intro. What do you say?

**Comment by prachi237** [comment] 2021-04-05 11:27
> > > I think we should not entirely remove this section from the intro. It forms the basis. FAQ is for more of technical (and profound) questions. Introduction should definitely have this part. Just my perspective. :)
> > > What do you think @viniciusdc ?
> > 
> > 
> > What I think, someone who is new to the org, won't be installing the packages or contribute in the first sight. He/she will first flick through the documentation first, and that is the main purpose of having a documentation for an organization. Hence according tto me we shd keep the intro brief and those questions can be added in the relevent sections, infact we have a complete separate section for that, reading those will make every thing clear for a new user.
> 
> But we also have to make it look appealing to them. If there is not a proper introduction, that might be a turn off. When we read something or start to watch something, the intro is what makes the first impression on us. We can't remove the What and Why conda-forge section for sure, that would not be good according to me. And @viniciusdc could better answer if we require a separate section for anything. Though I would still agree with you that the intro has to be re-modified any how. :)

aee no I am not asking to remove those two sections, I only had suggested to improve "what is conda-forge" definition

**Comment by prachi237** [comment] 2021-04-05 11:28
> > In addition in the issue #374 @ocefpaf had defined conda-forge really well, as someone new to org can easily understand it's purposesweat_smilesmile
> 
> I think we can take insights from it and come up with something good to redefine the intro. What do you say?

That's what I suggested 😅😄

**Comment by viniciusdc** [comment] 2021-04-05 12:27
great! @prachi237 and @PrernaSingh587 thanks for the discussion there, any new insights on this?

**Comment by viniciusdc** [comment] 2021-04-05 12:47
BTW, isn't this issue a duplicate of #1282 ?

**Comment by prachi237** [comment] 2021-04-05 12:58
> BTW, isn't this issue a duplicate of #1282 ?

 sir I just proposed to look into issue #374  where @ocefpaf had defined conda-forge really well, so if I can add that definition

**Comment by viniciusdc** [comment] 2021-04-05 15:48
yes, go ahead! :smile: every PR is welcomed

**Comment by PrernaSingh587** [comment] 2021-04-05 16:56
I have raised a PR for this. #1325 
You might wanna add to it. Suggestions are welcome.

**Comment by viniciusdc** [comment] 2021-04-05 20:26
HI @prachi237 @PrernaSingh587 would you mind closing this issue and post a brief comment in the '#1282' and link your PR there too, this will help us to not lose track of things. It can be the exact same content of this issue

**Closed** 2021-04-05 20:42 UTC
