### ISSUE TITLE
Pytorch package in conda-forge channel support win-64

### ISSUE THREAD

**Issue by haorenfsa** [conda-forge/conda-forge.github.io#1577] opened 2021-12-27 08:38 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I find that the conda-forge provides pytorch package, which is copied from `cf-staging / pytorch`, but not supports win-64. And The official channel `pytorch / pytorch ` already supports. Can you guys change the source? or find other ways to support win-64?  Our project based on pytorch need it to support win-64.

**Comment by isuruf** [comment] 2021-12-27 08:53
Duplicate of https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32

**Closed by isuruf** 2021-12-27 08:53 UTC
