### ISSUE TITLE
Not getting team membership after listing myself as a recipe maintainer

### ISSUE THREAD

**Issue by dalcinl** [conda-forge/conda-forge.github.io#332] opened 2017-02-08 18:21 UTC
After adding myself as a recipe maintainer of the `mpich` package (https://github.com/conda-forge/mpich-feedstock/blob/master/recipe/meta.yaml#L52), merged in conda-forge/mpich-feedstock#8 , I'm still not listed as a member of the @conda-forge/mpich team. I requested @ocefpaf to add me manually, but he asked me to open an issue here.

**Comment by kain88-de** [comment] 2017-02-08 21:22
Looks like a duplicate of #324

**Comment by ocefpaf** [comment] 2017-02-08 21:24
Thanks @kain88-de. Closing this then.

**Closed by ocefpaf** 2017-02-08 21:24 UTC

**Comment by jakirkham** [comment] 2017-02-10 06:12
As noted in the other issue, we are repeatedly running into GitHub rate limiting when adding all users to their teams. There is not much we can do with the current configuration as it is simply not sustainable as it scans all feedstocks and adds all members to all teams. It was a matter of time before it just got totally blocked from completion by rate limiting and we have reached that point in time.

If we want to restructure it to be more asynchronous like discussed in issue ( https://github.com/conda-forge/conda-forge-webservices/issues/63 ), we could fix it that way, but someone will need to have time to do it.
