### ISSUE TITLE
Azure pipelines failing with "no hosted parallelism purchased or granted" (2024 edition)

### ISSUE THREAD

**Issue by dbkeitel** [conda-forge/conda-forge.github.io#2218] opened 2024-07-04 15:08 UTC
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
n/a
```

### Environment info

```shell
m/a
```

### Issue

As several people have already reported on the old issue #1604 the same problem as back then is happening again today. Since I don't know if maintainers will notice reports on a closed issue, I'm reposting a new one here for consideration.

**Comment by ocefpaf** [comment] 2024-07-04 15:09
Duplicate of https://github.com/conda-forge/status/issues/181

Closing this so we can keep things in the status page.

PS: Note that due to the long weekend it is very likely this won't be solved before Monday.

**Closed by ocefpaf** 2024-07-04 15:09 UTC
Labels: bug
